# Generated by Django 6.0.4 on 2026-04-09 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Prix (FCFA)')),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Ancien prix (FCFA)')),
                ('description', models.TextField(verbose_name='Description')),
                ('specifications', models.JSONField(blank=True, default=dict, verbose_name='Caractéristiques')),
                ('status', models.CharField(choices=[('in_stock', 'En stock'), ('low_stock', 'Stock limité'), ('out_of_stock', 'Rupture de stock'), ('on_order', 'Sur commande')], default='in_stock', max_length=20, verbose_name='Disponibilité')),
                ('is_featured', models.BooleanField(default=False, verbose_name='En vedette')),
                ('is_new', models.BooleanField(default=True, verbose_name='Nouveau')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='brands.brand', verbose_name='Marque')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False, verbose_name='Image principale')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Image produit',
                'verbose_name_plural': 'Images produit',
                'ordering': ['order'],
            },
        ),
    ]
