"""
Commande Django pour creer des donnees de test.
Usage : python manage.py seed_data

Images :
- nova.sn  : produits verifies (pas de hotlink protection)
- unsplash : images produit generiques fiables
"""
import urllib.request
from django.core.management.base import BaseCommand
from django.core.files.base import ContentFile
from django.utils.text import slugify
from categories.models import Category
from brands.models import Brand
from products.models import Product, ProductImage


CATEGORIES = [
    {
        'name': 'Smartphones & Telephonie',
        'slug': 'smartphones-telephonie',
        'icon': 'Smartphone', 'order': 1,
        'image_url': 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&h=400&fit=crop&q=80',
        'children': [
            {'name': 'Smartphones', 'slug': 'smartphones', 'icon': 'Smartphone', 'order': 1},
            {'name': 'Telephones basiques', 'slug': 'telephones-basiques', 'icon': 'Phone', 'order': 2},
            {'name': 'Accessoires telephone', 'slug': 'accessoires-telephone', 'icon': 'Headphones', 'order': 3},
        ],
    },
    {
        'name': 'Informatique',
        'slug': 'informatique',
        'icon': 'Laptop', 'order': 2,
        'image_url': 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&h=400&fit=crop&q=80',
        'children': [
            {'name': 'Ordinateurs portables', 'slug': 'ordinateurs-portables', 'icon': 'Laptop', 'order': 1},
            {'name': 'Ordinateurs de bureau', 'slug': 'ordinateurs-bureau', 'icon': 'Monitor', 'order': 2},
            {'name': 'Tablettes', 'slug': 'tablettes', 'icon': 'Tablet', 'order': 3},
            {'name': 'Accessoires PC', 'slug': 'accessoires-pc', 'icon': 'Mouse', 'order': 4},
        ],
    },
    {
        'name': 'Electromenager',
        'slug': 'electromenager',
        'icon': 'Refrigerator', 'order': 3,
        'image_url': 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=400&fit=crop&q=80',
        'children': [
            {'name': 'Refrigerateurs', 'slug': 'refrigerateurs', 'icon': 'Refrigerator', 'order': 1},
            {'name': 'Machines a laver', 'slug': 'machines-laver', 'icon': 'WashingMachine', 'order': 2},
            {'name': 'Climatiseurs', 'slug': 'climatiseurs', 'icon': 'Wind', 'order': 3},
            {'name': 'Televiseurs', 'slug': 'televiseurs', 'icon': 'Tv', 'order': 4},
            {'name': 'Petits electromenagers', 'slug': 'petits-electromenagers', 'icon': 'Zap', 'order': 5},
            {'name': 'Onduleurs & Solaire', 'slug': 'onduleurs-solaire', 'icon': 'Sun', 'order': 6},
        ],
    },
    {
        'name': 'Audio & Video',
        'slug': 'audio-video',
        'icon': 'Speaker', 'order': 4,
        'image_url': 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600&h=400&fit=crop&q=80',
        'children': [
            {'name': 'Home cinema', 'slug': 'home-cinema', 'icon': 'Film', 'order': 1},
            {'name': 'Enceintes Bluetooth', 'slug': 'enceintes-bluetooth', 'icon': 'Speaker', 'order': 2},
            {'name': 'Cameras & Surveillance', 'slug': 'cameras-surveillance', 'icon': 'Camera', 'order': 3},
        ],
    },
    {
        'name': 'Jeux video',
        'slug': 'jeux-video',
        'icon': 'Gamepad2', 'order': 5,
        'image_url': 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=600&h=400&fit=crop&q=80',
        'children': [
            {'name': 'Consoles', 'slug': 'consoles', 'icon': 'Gamepad2', 'order': 1},
            {'name': 'Manettes & Accessoires', 'slug': 'manettes-accessoires', 'icon': 'Gamepad', 'order': 2},
        ],
    },
]

BRANDS = [
    'Samsung', 'Apple', 'Huawei', 'Xiaomi', 'Tecno',
    'Infinix', 'itel', 'LG', 'Hisense', 'Sony',
    'HP', 'Lenovo', 'Asus', 'Acer', 'Dell',
    'JBL', 'Philips', 'Bosch', 'Whirlpool', 'Haier', 'Midea',
    'Microsoft', 'Nintendo',
]

FEATURED_BRANDS = ['Samsung', 'Apple', 'Xiaomi', 'Tecno', 'LG', 'HP', 'Haier', 'Hisense']

SAMPLE_PRODUCTS = [

    # ── SMARTPHONES ──────────────────────────────────────────────────────────
    {
        'name': 'Samsung Galaxy Z Flip 6 256Go',
        'slug': 'samsung-galaxy-z-flip-6-256go',
        'category_slug': 'smartphones',
        'brand': 'Samsung',
        'price': 625000,
        'old_price': 680000,
        'status': 'in_stock',
        'is_featured': True,
        'is_new': True,
        'image_url': 'https://nova.sn/34321-home_default/samsung-galaxy-z-flip-6-12-go-de-ram-memoire-256-go.jpg',
        'description': 'Samsung Galaxy Z Flip 6 pliable avec ecran Dynamic AMOLED 6.7 pouces, Snapdragon 8 Gen 3, 12 Go RAM et appareil photo 50 MP.',
        'specifications': {
            'Ecran': '6.7 pouces Dynamic AMOLED 2X 120Hz (pliable)',
            'Processeur': 'Snapdragon 8 Gen 3',
            'RAM': '12 Go', 'Stockage': '256 Go',
            'Appareil photo': '50 + 12 MP',
            'Batterie': '4000 mAh, charge 25W',
            'Systeme': 'Android 14 (One UI 6.1)',
            'Connectivite': '5G, WiFi 7, Bluetooth 5.3, NFC',
        },
    },
    {
        'name': 'Samsung Galaxy S24 Ultra 256Go',
        'slug': 'samsung-galaxy-s24-ultra-256go',
        'category_slug': 'smartphones',
        'brand': 'Samsung',
        'price': 899000,
        'old_price': 999000,
        'status': 'in_stock',
        'is_featured': True,
        'is_new': True,
        'image_url': 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400&h=400&fit=crop&q=80',
        'description': 'Samsung Galaxy S24 Ultra avec stylet S Pen integre, appareil photo 200 MP et intelligence artificielle Galaxy AI.',
        'specifications': {
            'Ecran': '6.8 pouces Dynamic AMOLED 2X 120Hz',
            'Processeur': 'Snapdragon 8 Gen 3',
            'RAM': '12 Go', 'Stockage': '256 Go',
            'Appareil photo': '200 + 50 + 12 + 10 MP',
            'Batterie': '5000 mAh, charge 45W',
            'Systeme': 'Android 14 (One UI 6.1)',
            'S Pen': 'Integre',
        },
    },
    {
        'name': 'Samsung Galaxy A55 5G 128Go',
        'slug': 'samsung-galaxy-a55-5g-128go',
        'category_slug': 'smartphones',
        'brand': 'Samsung',
        'price': 295000,
        'old_price': 330000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': True,
        'image_url': 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400&h=400&fit=crop&q=80',
        'description': 'Samsung Galaxy A55 5G avec ecran Super AMOLED 6.6 pouces 120Hz, triple camera 50 MP et batterie 5000 mAh.',
        'specifications': {
            'Ecran': '6.6 pouces Super AMOLED 120Hz',
            'Processeur': 'Exynos 1480',
            'RAM': '8 Go', 'Stockage': '128 Go',
            'Appareil photo': '50 + 12 + 5 MP',
            'Batterie': '5000 mAh, charge 25W',
            'Systeme': 'Android 14',
        },
    },
    {
        'name': 'iPhone 15 128Go Noir',
        'slug': 'iphone-15-128go-noir',
        'category_slug': 'smartphones',
        'brand': 'Apple',
        'price': 649000,
        'old_price': 720000,
        'status': 'in_stock',
        'is_featured': True,
        'is_new': True,
        'image_url': 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&h=400&fit=crop&q=80',
        'description': 'iPhone 15 avec puce A16 Bionic, Dynamic Island, appareil photo 48 MP et port USB-C pour la premiere fois.',
        'specifications': {
            'Ecran': '6.1 pouces Super Retina XDR OLED',
            'Processeur': 'A16 Bionic',
            'Stockage': '128 Go',
            'Appareil photo': '48 + 12 MP',
            'Batterie': '3349 mAh',
            'Systeme': 'iOS 17',
            'Connectivite': 'USB-C, WiFi 6, Bluetooth 5.3',
        },
    },
    {
        'name': 'iPhone 15 Pro 256Go Titane',
        'slug': 'iphone-15-pro-256go-titane',
        'category_slug': 'smartphones',
        'brand': 'Apple',
        'price': 869000,
        'old_price': None,
        'status': 'low_stock',
        'is_featured': True,
        'is_new': True,
        'image_url': 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&h=400&fit=crop&q=80',
        'description': 'iPhone 15 Pro en titane avec puce A17 Pro, bouton Action programmable, appareil photo Pro 48 MP et zoom optique 3x.',
        'specifications': {
            'Ecran': '6.1 pouces Super Retina XDR ProMotion 120Hz',
            'Processeur': 'A17 Pro',
            'Stockage': '256 Go',
            'Appareil photo': '48 + 12 + 12 MP (Telephoto 3x)',
            'Batterie': '3274 mAh',
            'Systeme': 'iOS 17',
            'Chassis': 'Titane grade 5',
        },
    },
    {
        'name': 'Huawei Nova 12 SE 256Go',
        'slug': 'huawei-nova-12-se-256go',
        'category_slug': 'smartphones',
        'brand': 'Huawei',
        'price': 245000,
        'old_price': 280000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': True,
        'image_url': 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop&q=80',
        'description': 'Huawei Nova 12 SE avec appareil photo 108 MP, ecran OLED 6.67 pouces et charge rapide 100W.',
        'specifications': {
            'Ecran': '6.67 pouces OLED 90Hz',
            'Processeur': 'Snapdragon 680',
            'RAM': '8 Go', 'Stockage': '256 Go',
            'Appareil photo': '108 + 2 MP',
            'Batterie': '4500 mAh, charge 100W',
            'Systeme': 'HarmonyOS 4.0',
        },
    },
    {
        'name': 'Xiaomi Redmi Note 13 Pro 256Go',
        'slug': 'xiaomi-redmi-note-13-pro-256go',
        'category_slug': 'smartphones',
        'brand': 'Xiaomi',
        'price': 185000,
        'old_price': 210000,
        'status': 'in_stock',
        'is_featured': True,
        'is_new': True,
        'image_url': 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop&q=80',
        'description': 'Xiaomi Redmi Note 13 Pro avec appareil photo 200 MP, ecran AMOLED 6.67 pouces 120Hz et charge 67W.',
        'specifications': {
            'Ecran': '6.67 pouces AMOLED 120Hz',
            'Processeur': 'Dimensity 7200 Ultra',
            'RAM': '12 Go', 'Stockage': '256 Go',
            'Appareil photo': '200 + 8 + 2 MP',
            'Batterie': '5100 mAh, charge 67W',
            'Systeme': 'MIUI 14 (Android 13)',
        },
    },
    {
        'name': 'Redmi A3x 64 Go',
        'slug': 'redmi-a3x-64go',
        'category_slug': 'smartphones',
        'brand': 'Xiaomi',
        'price': 39000,
        'old_price': None,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': True,
        'image_url': 'https://nova.sn/34000-home_default/redmi-a3x-memoire-64-go-ram-3-go-ecran-671.jpg',
        'description': 'Redmi A3x : smartphone economique avec ecran 6.71 pouces et batterie 5000 mAh longue duree.',
        'specifications': {
            'Ecran': '6.71 pouces HD+', 'Processeur': 'Helio G36',
            'RAM': '3 Go', 'Stockage': '64 Go',
            'Appareil photo': '8 MP', 'Batterie': '5000 mAh',
            'Systeme': 'Android 14 Go',
        },
    },
    {
        'name': 'Tecno POP 9 64 Go',
        'slug': 'tecno-pop-9-64go',
        'category_slug': 'smartphones',
        'brand': 'Tecno',
        'price': 50000,
        'old_price': 60000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': True,
        'image_url': 'https://nova.sn/34118-home_default/tecno-pop-9-memoire-64-go-ram-3-go-ecran-667-pouces.jpg',
        'description': 'Tecno POP 9 avec ecran 6.67 pouces HD+ 90Hz, appareil photo IA et batterie 5000 mAh. Meilleur rapport qualite/prix.',
        'specifications': {
            'Ecran': '6.67 pouces HD+ 90Hz', 'Processeur': 'Helio A22',
            'RAM': '3 Go', 'Stockage': '64 Go',
            'Appareil photo': '8 MP IA', 'Batterie': '5000 mAh',
            'Systeme': 'Android 14 Go',
        },
    },
    {
        'name': 'Tecno Spark 30c 128 Go',
        'slug': 'tecno-spark-30c-128go',
        'category_slug': 'smartphones',
        'brand': 'Tecno',
        'price': 63000,
        'old_price': 75000,
        'status': 'in_stock',
        'is_featured': True,
        'is_new': True,
        'image_url': 'https://nova.sn/34424-home_default/tecno-pop-9-memoire-64-go-ram-3-go-ecran-667-pouces.jpg',
        'description': 'Tecno Spark 30c 128 Go avec ecran AMOLED 6.6 pouces 90Hz, Helio G85 et charge 18W.',
        'specifications': {
            'Ecran': '6.6 pouces AMOLED 90Hz', 'Processeur': 'Helio G85',
            'RAM': '4 Go', 'Stockage': '128 Go',
            'Appareil photo': '13 MP', 'Batterie': '5000 mAh, charge 18W',
            'Systeme': 'Android 14',
        },
    },
    {
        'name': 'Infinix Hot 40 Pro 256Go',
        'slug': 'infinix-hot-40-pro-256go',
        'category_slug': 'smartphones',
        'brand': 'Infinix',
        'price': 89000,
        'old_price': 105000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': True,
        'image_url': 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop&q=80',
        'description': 'Infinix Hot 40 Pro avec ecran AMOLED 6.78 pouces 120Hz, Helio G99 et triple camera 108 MP.',
        'specifications': {
            'Ecran': '6.78 pouces AMOLED 120Hz',
            'Processeur': 'Helio G99',
            'RAM': '8 Go', 'Stockage': '256 Go',
            'Appareil photo': '108 + 2 + 2 MP',
            'Batterie': '5000 mAh, charge 45W',
            'Systeme': 'XOS 13.5 (Android 13)',
        },
    },
    {
        'name': 'itel A70 128Go',
        'slug': 'itel-a70-128go',
        'category_slug': 'smartphones',
        'brand': 'itel',
        'price': 45000,
        'old_price': 52000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop&q=80',
        'description': 'itel A70 smartphone entree de gamme avec grand ecran 6.6 pouces, batterie longue duree 5000 mAh et stockage 128 Go.',
        'specifications': {
            'Ecran': '6.6 pouces HD+ 90Hz',
            'Processeur': 'Unisoc T606',
            'RAM': '4 Go', 'Stockage': '128 Go',
            'Appareil photo': '13 MP + 0.08 MP',
            'Batterie': '5000 mAh',
            'Systeme': 'Android 13 Go',
        },
    },
    {
        'name': 'Sony Xperia 5 V 128Go',
        'slug': 'sony-xperia-5-v-128go',
        'category_slug': 'smartphones',
        'brand': 'Sony',
        'price': 520000,
        'old_price': 590000,
        'status': 'low_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop&q=80',
        'description': 'Sony Xperia 5 V compact avec ecran OLED 6.1 pouces 120Hz, Snapdragon 8 Gen 2 et appareil photo Sony Zeiss 48 MP.',
        'specifications': {
            'Ecran': '6.1 pouces FHD+ OLED 120Hz HDR',
            'Processeur': 'Snapdragon 8 Gen 2',
            'RAM': '8 Go', 'Stockage': '128 Go',
            'Appareil photo': '48 + 12 MP (Zeiss)',
            'Batterie': '5000 mAh, charge 30W',
            'Etancheite': 'IP65/68',
        },
    },

    # ── TELEPHONES BASIQUES ───────────────────────────────────────────────────
    {
        'name': 'itel it2163 Double SIM',
        'slug': 'itel-it2163-double-sim',
        'category_slug': 'telephones-basiques',
        'brand': 'itel',
        'price': 12000,
        'old_price': None,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop&q=80',
        'description': 'Telephone basique itel double SIM avec clavier physique, radio FM et batterie 1000 mAh longue duree. Ideal pour second telephone.',
        'specifications': {
            'Type': 'Telephone basique',
            'SIM': 'Double SIM',
            'Radio': 'FM integree',
            'Batterie': '1000 mAh',
            'Couleur': 'Noir',
        },
    },
    {
        'name': 'Samsung Guru B310E Double SIM',
        'slug': 'samsung-guru-b310e',
        'category_slug': 'telephones-basiques',
        'brand': 'Samsung',
        'price': 18000,
        'old_price': 22000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop&q=80',
        'description': 'Samsung Guru B310E telephone double SIM robuste avec batterie 1000 mAh, radio FM et lampe torche integree.',
        'specifications': {
            'Type': 'Telephone basique',
            'SIM': 'Double SIM',
            'Radio': 'FM + MP3',
            'Batterie': '1000 mAh',
            'Lampe torche': 'Oui',
        },
    },

    # ── ACCESSOIRES TELEPHONE ─────────────────────────────────────────────────
    {
        'name': 'Samsung Galaxy Buds2 Pro',
        'slug': 'samsung-galaxy-buds2-pro',
        'category_slug': 'accessoires-telephone',
        'brand': 'Samsung',
        'price': 95000,
        'old_price': 119000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop&q=80',
        'description': 'Samsung Galaxy Buds2 Pro ecouteurs sans fil avec ANC intelligent, son Hi-Fi 24bit et resistance IPX7.',
        'specifications': {
            'Type': 'Ecouteurs intra-auriculaires TWS',
            'ANC': 'Active Noise Cancellation intelligent',
            'Son': 'Hi-Fi 24bit avec Dolby Atmos',
            'Autonomie': '5h (29h avec boitier)',
            'Etancheite': 'IPX7',
            'Bluetooth': '5.3',
        },
    },
    {
        'name': 'Chargeur Rapide Samsung 45W USB-C',
        'slug': 'chargeur-rapide-samsung-45w-usb-c',
        'category_slug': 'accessoires-telephone',
        'brand': 'Samsung',
        'price': 18000,
        'old_price': 25000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1588702547919-26089e690ecc?w=400&h=400&fit=crop&q=80',
        'description': 'Chargeur rapide Samsung 45W USB-C compatible Super Fast Charging 2.0 pour Galaxy S et Note.',
        'specifications': {
            'Puissance': '45W',
            'Connecteur': 'USB-C',
            'Technologie': 'Super Fast Charging 2.0',
            'Compatible': 'Samsung Galaxy S21+ et superieur',
        },
    },
    {
        'name': 'JBL Tune 510BT Casque Bluetooth',
        'slug': 'jbl-tune-510bt-casque-bluetooth',
        'category_slug': 'accessoires-telephone',
        'brand': 'JBL',
        'price': 29000,
        'old_price': 39000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&q=80',
        'description': "Casque JBL Tune 510BT sans fil Bluetooth 5.0 avec 40h d'autonomie et son JBL Pure Bass. Confortable et leger.",
        'specifications': {
            'Type': 'Casque circum-aural',
            'Bluetooth': '5.0',
            'Autonomie': '40h',
            'Charge': 'USB-C, 2h pour charge complete',
            'Poids': '160g',
            'Microphone': 'Integre (mains libres)',
        },
    },

    # ── ORDINATEURS PORTABLES ─────────────────────────────────────────────────
    {
        'name': 'Lenovo IdeaPad Slim 3 Core i5 16Go',
        'slug': 'lenovo-ideapad-slim-3-core-i5-16go',
        'category_slug': 'ordinateurs-portables',
        'brand': 'Lenovo',
        'price': 380000,
        'old_price': 430000,
        'status': 'in_stock',
        'is_featured': True,
        'is_new': True,
        'image_url': 'https://nova.sn/41278-home_default/lenovo-ideapad-slim-3-pc-portable-14-core-i5-16-go-ram-512-go-ssd.jpg',
        'description': 'Lenovo IdeaPad Slim 3 14 pouces avec Intel Core i5, 16 Go RAM et SSD 512 Go. Ultra-fin et performant pour travail et etudes.',
        'specifications': {
            'Ecran': '14 pouces FHD IPS', 'Processeur': 'Intel Core i5 (12e gen)',
            'RAM': '16 Go DDR4', 'Stockage': 'SSD 512 Go NVMe',
            'Graphique': 'Intel Iris Xe', 'Systeme': 'Windows 11 Home',
            'Poids': '1.4 kg',
        },
    },
    {
        'name': 'HP Pavilion 15 Core i7 16Go 512Go',
        'slug': 'hp-pavilion-15-core-i7-16go-512go',
        'category_slug': 'ordinateurs-portables',
        'brand': 'HP',
        'price': 495000,
        'old_price': 560000,
        'status': 'in_stock',
        'is_featured': True,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop&q=80',
        'description': 'HP Pavilion 15 avec Intel Core i7 13e gen, 16 Go RAM DDR5, SSD 512 Go et ecran FHD IPS antireflexion. Puissant et polyvalent.',
        'specifications': {
            'Ecran': '15.6 pouces FHD IPS antireflexion',
            'Processeur': 'Intel Core i7-1355U (13e gen)',
            'RAM': '16 Go DDR5', 'Stockage': 'SSD 512 Go NVMe',
            'Graphique': 'Intel Iris Xe + NVIDIA GeForce MX550',
            'Systeme': 'Windows 11 Home',
            'Poids': '1.75 kg',
        },
    },
    {
        'name': 'Asus VivoBook 15 Core i5 8Go',
        'slug': 'asus-vivobook-15-core-i5-8go',
        'category_slug': 'ordinateurs-portables',
        'brand': 'Asus',
        'price': 329000,
        'old_price': 369000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': True,
        'image_url': 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop&q=80',
        'description': "Asus VivoBook 15 avec Intel Core i5, 8 Go RAM, SSD 256 Go et ecran 15.6 pouces FHD. Design moderne avec lecteur d'empreinte.",
        'specifications': {
            'Ecran': '15.6 pouces FHD IPS',
            'Processeur': 'Intel Core i5-1235U',
            'RAM': '8 Go DDR4', 'Stockage': 'SSD 256 Go',
            'Graphique': 'Intel Iris Xe',
            'Systeme': 'Windows 11 Home',
            'Securite': "Lecteur d'empreinte digitale",
        },
    },
    {
        'name': 'Acer Aspire 5 Core i3 8Go',
        'slug': 'acer-aspire-5-core-i3-8go',
        'category_slug': 'ordinateurs-portables',
        'brand': 'Acer',
        'price': 249000,
        'old_price': 289000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop&q=80',
        'description': 'Acer Aspire 5 avec Intel Core i3 12e gen, 8 Go RAM, SSD 256 Go et ecran 15.6 pouces. Parfait pour etudes et bureau.',
        'specifications': {
            'Ecran': '15.6 pouces FHD',
            'Processeur': 'Intel Core i3-1215U (12e gen)',
            'RAM': '8 Go DDR4', 'Stockage': 'SSD 256 Go',
            'Systeme': 'Windows 11 Home',
            'Connectique': 'USB-C, HDMI, USB 3.2',
        },
    },
    {
        'name': 'Dell Inspiron 15 Core i5 16Go',
        'slug': 'dell-inspiron-15-core-i5-16go',
        'category_slug': 'ordinateurs-portables',
        'brand': 'Dell',
        'price': 415000,
        'old_price': None,
        'status': 'on_order',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop&q=80',
        'description': 'Dell Inspiron 15 3000 avec Intel Core i5, 16 Go RAM et SSD 512 Go. Fiabilite Dell pour un usage quotidien intensif.',
        'specifications': {
            'Ecran': '15.6 pouces FHD antireflet',
            'Processeur': 'Intel Core i5-1235U',
            'RAM': '16 Go DDR4', 'Stockage': 'SSD 512 Go',
            'Graphique': 'Intel UHD',
            'Systeme': 'Windows 11 Home',
        },
    },
    {
        'name': 'Lenovo Yoga Tab Plus 12.7" 16Go',
        'slug': 'lenovo-yoga-tab-plus-127-16go',
        'category_slug': 'tablettes',
        'brand': 'Lenovo',
        'price': 450000,
        'old_price': 499000,
        'status': 'in_stock',
        'is_featured': True,
        'is_new': True,
        'image_url': 'https://nova.sn/41644-home_default/lenovo-yoga-tab-plus-127-3k-16-go-ram-256-go-clavier-et-stylet.jpg',
        'description': 'Lenovo Yoga Tab Plus 12.7 pouces ecran 3K, 16 Go RAM, 256 Go, avec clavier et stylet inclus. La tablette pro ultime.',
        'specifications': {
            'Ecran': '12.7 pouces 3K (2944x1840)', 'Processeur': 'Snapdragon 870',
            'RAM': '16 Go', 'Stockage': '256 Go',
            'Batterie': '10200 mAh', 'Systeme': 'Android 13',
            'Accessoires': 'Clavier + Stylet inclus',
        },
    },

    # ── ORDINATEURS DE BUREAU ─────────────────────────────────────────────────
    {
        'name': 'HP ProDesk 400 G9 Core i5 Mini PC',
        'slug': 'hp-prodesk-400-g9-core-i5-mini',
        'category_slug': 'ordinateurs-bureau',
        'brand': 'HP',
        'price': 289000,
        'old_price': 330000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1587614382346-4ec70e388b28?w=400&h=400&fit=crop&q=80',
        'description': 'HP ProDesk 400 G9 Mini PC Core i5 ultra-compact avec 8 Go RAM, SSD 256 Go. Ideal pour bureau et espace reduit.',
        'specifications': {
            'Format': 'Mini PC',
            'Processeur': 'Intel Core i5-12500T',
            'RAM': '8 Go DDR5', 'Stockage': 'SSD 256 Go NVMe',
            'Systeme': 'Windows 11 Pro',
            'Connectique': 'USB-C Thunderbolt, USB 3.2, DisplayPort, HDMI',
        },
    },

    # ── TABLETTES ─────────────────────────────────────────────────────────────
    {
        'name': 'Samsung Galaxy Tab A9+ 5G 128Go',
        'slug': 'samsung-galaxy-tab-a9-plus-5g-128go',
        'category_slug': 'tablettes',
        'brand': 'Samsung',
        'price': 235000,
        'old_price': 270000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': True,
        'image_url': 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop&q=80',
        'description': 'Samsung Galaxy Tab A9+ 5G avec grand ecran 11 pouces FHD+, Snapdragon 695 et 8 haut-parleurs Dolby Atmos.',
        'specifications': {
            'Ecran': '11 pouces FHD+ 90Hz',
            'Processeur': 'Snapdragon 695',
            'RAM': '8 Go', 'Stockage': '128 Go',
            'Batterie': '7040 mAh', 'Systeme': 'Android 13',
            'Son': '4 haut-parleurs Dolby Atmos',
        },
    },
    {
        'name': 'Huawei MatePad 11.5" 8Go',
        'slug': 'huawei-matepad-11-5-8go',
        'category_slug': 'tablettes',
        'brand': 'Huawei',
        'price': 299000,
        'old_price': 340000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop&q=80',
        'description': 'Huawei MatePad 11.5 pouces avec ecran IPS 2K 120Hz, Kirin 9000W et HarmonyOS 4.0.',
        'specifications': {
            'Ecran': '11.5 pouces IPS 2K 120Hz',
            'Processeur': 'Kirin 9000W',
            'RAM': '8 Go', 'Stockage': '128 Go',
            'Batterie': '8800 mAh', 'Systeme': 'HarmonyOS 4.0',
        },
    },

    # ── ACCESSOIRES PC ────────────────────────────────────────────────────────
    {
        'name': 'HP Moniteur 27" FHD IPS 75Hz',
        'slug': 'hp-moniteur-27-fhd-ips-75hz',
        'category_slug': 'accessoires-pc',
        'brand': 'HP',
        'price': 125000,
        'old_price': 145000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://nova.sn/42229-home_default/hp-p27-g5-moniteur-27-full-hd-ips-75hz-hdmi-displayport.jpg',
        'description': 'Moniteur HP P27 G5 27 pouces Full HD IPS 75Hz avec entrees HDMI et DisplayPort. Ideal pour le bureau.',
        'specifications': {
            'Taille': '27 pouces', 'Resolution': 'Full HD (1920x1080)',
            'Panneau': 'IPS', 'Taux de rafraichissement': '75Hz',
            'Temps de reponse': '5ms', 'Connectique': 'HDMI, DisplayPort, VGA',
        },
    },
    {
        'name': 'HP Moniteur 24" Full HD 60Hz',
        'slug': 'hp-moniteur-24-fhd-60hz',
        'category_slug': 'accessoires-pc',
        'brand': 'HP',
        'price': 85000,
        'old_price': 99000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&h=400&fit=crop&q=80',
        'description': 'Moniteur HP 24 pouces Full HD VA antireflet avec port HDMI et VGA. Economique et fiable pour usage quotidien.',
        'specifications': {
            'Taille': '24 pouces', 'Resolution': 'Full HD (1920x1080)',
            'Panneau': 'VA', 'Taux de rafraichissement': '60Hz',
            'Temps de reponse': '5ms', 'Connectique': 'HDMI, VGA',
        },
    },
    {
        'name': 'Clavier + Souris Sans Fil HP 235',
        'slug': 'clavier-souris-sans-fil-hp-235',
        'category_slug': 'accessoires-pc',
        'brand': 'HP',
        'price': 15000,
        'old_price': 20000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&h=400&fit=crop&q=80',
        'description': "Pack clavier et souris sans fil HP 235 avec recepteur USB nano 2.4 GHz. Autonomie jusqu'a 12 mois clavier et 18 mois souris.",
        'specifications': {
            'Type': 'Pack clavier + souris',
            'Connexion': 'Sans fil 2.4 GHz',
            'Recepteur': 'USB nano unique',
            'Autonomie clavier': '12 mois',
            'Autonomie souris': '18 mois',
        },
    },

    # ── TELEVISEURS ───────────────────────────────────────────────────────────
    {
        'name': 'Samsung TV LED 55" 4K Smart',
        'slug': 'samsung-tv-led-55-4k-smart',
        'category_slug': 'televiseurs',
        'brand': 'Samsung',
        'price': 270000,
        'old_price': 320000,
        'status': 'in_stock',
        'is_featured': True,
        'is_new': False,
        'image_url': 'https://nova.sn/42102-home_default/samsung-tv-led-55u8072-55-smart-tv-4k-uhd.jpg',
        'description': 'Samsung TV LED 55 pouces 4K UHD Smart avec Crystal 4K, HDR10+ et Netflix/YouTube/Prime Video integres.',
        'specifications': {
            'Taille': '55 pouces', 'Resolution': '4K UHD (3840x2160)',
            'HDR': 'HDR10+', 'Smart TV': 'Tizen OS',
            'Connectique': 'HDMI x3, USB x2, WiFi, Bluetooth',
            'Garantie': '1 an',
        },
    },
    {
        'name': 'Samsung TV QLED 65" 4K Neo',
        'slug': 'samsung-tv-qled-65-4k-neo',
        'category_slug': 'televiseurs',
        'brand': 'Samsung',
        'price': 695000,
        'old_price': 799000,
        'status': 'in_stock',
        'is_featured': True,
        'is_new': True,
        'image_url': 'https://images.unsplash.com/photo-1593359677879-a4bb92f4834c?w=400&h=400&fit=crop&q=80',
        'description': 'Samsung Neo QLED 65 pouces 4K avec technologie Mini LED, processeur Neural Quantum et Dolby Atmos.',
        'specifications': {
            'Taille': '65 pouces', 'Technologie': 'Neo QLED Mini-LED',
            'Resolution': '4K UHD', 'HDR': 'Quantum HDR 2000',
            'Smart TV': 'Tizen OS', 'Son': 'Dolby Atmos Object Tracking Sound',
            'Connectique': 'HDMI 2.1 x4, USB x2, WiFi 6',
        },
    },
    {
        'name': 'LG 70" Smart TV 4K UHD ThinQ AI',
        'slug': 'lg-70-smart-tv-4k-thinq-ai',
        'category_slug': 'televiseurs',
        'brand': 'LG',
        'price': 495000,
        'old_price': 560000,
        'status': 'in_stock',
        'is_featured': True,
        'is_new': False,
        'image_url': 'https://nova.sn/42223-home_default/lg-70-smart-tv-4k-up7550pvd-uhd-hdr-webos-thinq-ai.jpg',
        'description': 'LG Smart TV 70 pouces 4K UHD avec webOS 22, ThinQ AI, Magic Remote et Dolby Vision. Experience cinema chez vous.',
        'specifications': {
            'Taille': '70 pouces', 'Resolution': '4K UHD (3840x2160)',
            'HDR': 'Dolby Vision, HDR10, HLG', 'Smart TV': 'webOS 22',
            'IA': 'ThinQ AI + Google Assistant',
            'Connectique': 'HDMI x3, USB x2, WiFi, Bluetooth',
        },
    },
    {
        'name': 'LG NanoCell 75" Smart TV 4K',
        'slug': 'lg-nanocell-75-smart-tv-4k',
        'category_slug': 'televiseurs',
        'brand': 'LG',
        'price': 610000,
        'old_price': 699000,
        'status': 'in_stock',
        'is_featured': True,
        'is_new': False,
        'image_url': 'https://nova.sn/42233-home_default/lg-nanocell-75nano80-75-smart-tv-4k-hdr10-webos24-ai-magic-remote.jpg',
        'description': 'LG NanoCell 75 pouces 4K avec technologie NanoCell pour des couleurs pures, webOS 24 et Magic Remote.',
        'specifications': {
            'Taille': '75 pouces', 'Technologie': 'NanoCell',
            'Resolution': '4K UHD', 'Smart TV': 'webOS 24',
            'HDR': 'HDR10, HLG',
            'Connectique': 'HDMI x4, USB x3, WiFi, Bluetooth',
        },
    },
    {
        'name': 'Haier Mini-LED 65" 4K Google TV',
        'slug': 'haier-mini-led-65-4k-google-tv',
        'category_slug': 'televiseurs',
        'brand': 'Haier',
        'price': 435000,
        'old_price': 490000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': True,
        'image_url': 'https://nova.sn/41600-home_default/televiseur-haier-mini-led-65-pouces-4k-google-tv-h65m80fux.jpg',
        'description': 'Haier Mini-LED 65 pouces 4K Google TV avec contraste exceptionnel et commande vocale integree.',
        'specifications': {
            'Taille': '65 pouces', 'Technologie': 'Mini-LED',
            'Resolution': '4K UHD', 'Smart TV': 'Google TV',
            'HDR': 'Dolby Vision, HDR10+',
            'Connectique': 'HDMI x4, USB x3, WiFi 6, Bluetooth 5.1',
            'Garantie': '2 ans',
        },
    },
    {
        'name': 'Hisense VIDAA 43" 4K Smart TV',
        'slug': 'hisense-vidaa-43-4k-smart-tv',
        'category_slug': 'televiseurs',
        'brand': 'Hisense',
        'price': 165000,
        'old_price': 195000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': True,
        'image_url': 'https://images.unsplash.com/photo-1593359677879-a4bb92f4834c?w=400&h=400&fit=crop&q=80',
        'description': 'Hisense 43 pouces 4K Smart TV avec VIDAA OS, Dolby Vision et DTS Virtual X. Excellent rapport qualite/prix.',
        'specifications': {
            'Taille': '43 pouces', 'Resolution': '4K UHD',
            'Smart TV': 'VIDAA 7.0', 'HDR': 'Dolby Vision, HDR10+',
            'Son': 'DTS Virtual X',
            'Connectique': 'HDMI x3, USB x2, WiFi, Bluetooth',
        },
    },
    {
        'name': 'Sony Bravia 55" 4K OLED Google TV',
        'slug': 'sony-bravia-55-4k-oled-google-tv',
        'category_slug': 'televiseurs',
        'brand': 'Sony',
        'price': 889000,
        'old_price': None,
        'status': 'low_stock',
        'is_featured': True,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1593359677879-a4bb92f4834c?w=400&h=400&fit=crop&q=80',
        'description': 'Sony Bravia 55 pouces OLED 4K avec processeur XR Cognitive, son Acoustic Surface Audio+ et Google TV.',
        'specifications': {
            'Taille': '55 pouces', 'Technologie': 'OLED',
            'Resolution': '4K UHD', 'Processeur': 'XR Cognitive',
            'Smart TV': 'Google TV',
            'Son': 'Acoustic Surface Audio+ Dolby Atmos',
            'Connectique': 'HDMI 2.1 x4, USB x3, WiFi 6',
        },
    },

    # ── CLIMATISEURS ──────────────────────────────────────────────────────────
    {
        'name': 'LG Split 12000 BTU Anti-Moustique Inverter',
        'slug': 'lg-split-12000-btu-anti-moustique-inverter',
        'category_slug': 'climatiseurs',
        'brand': 'LG',
        'price': 320000,
        'old_price': 365000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://nova.sn/35808-home_default/split-lg-12000btu-anti-moustique-refroidissement-puissant.jpg',
        'description': 'Climatiseur LG Split 12000 BTU avec technologie Anti-Moustique, Dual Inverter et WiFi ThinQ. Classe A++.',
        'specifications': {
            'Puissance': '12 000 BTU (1.5 CV)',
            'Technologie': 'Dual Inverter + Anti-Moustique',
            'WiFi': 'Oui (ThinQ)',
            'Classe energetique': 'A++',
            'Mode': 'Chaud/Froid',
            'Garantie compresseur': '10 ans',
        },
    },
    {
        'name': 'LG Split 18000 BTU Anti-Moustique Inverter',
        'slug': 'lg-split-18000-btu-anti-moustique-inverter',
        'category_slug': 'climatiseurs',
        'brand': 'LG',
        'price': 420000,
        'old_price': None,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://nova.sn/35803-home_default/split-lg-18000btu-anti-moustique-inverter-puissant.jpg',
        'description': 'Climatiseur LG Split 18000 BTU/h 2 CV Anti-Moustique Inverter. Ideal pour grandes pieces 25-40 m2.',
        'specifications': {
            'Puissance': '18 000 BTU (2 CV)',
            'Technologie': 'Dual Inverter + Anti-Moustique',
            'WiFi': 'Oui (ThinQ)',
            'Classe energetique': 'A++',
            'Mode': 'Chaud/Froid',
            'Garantie compresseur': '10 ans',
        },
    },
    {
        'name': 'Midea Split 24000 BTU 3CV Inverter',
        'slug': 'midea-split-24000-btu-3cv-inverter',
        'category_slug': 'climatiseurs',
        'brand': 'Midea',
        'price': 350000,
        'old_price': 390000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://nova.sn/35701-home_default/split-midea-24000-btu-3-cv-gaz-410.jpg',
        'description': 'Climatiseur Midea Split 24000 BTU 3 CV Inverter Gaz R410. Solution economique et performante pour grandes surfaces.',
        'specifications': {
            'Puissance': '24 000 BTU (3 CV)',
            'Technologie': 'Inverter Gaz R410',
            'Classe energetique': 'A+',
            'Mode': 'Chaud/Froid',
            'Surface recommandee': '40-60 m2',
        },
    },
    {
        'name': 'Samsung Split 9000 BTU WindFree Inverter',
        'slug': 'samsung-split-9000-btu-windfree-inverter',
        'category_slug': 'climatiseurs',
        'brand': 'Samsung',
        'price': 280000,
        'old_price': 320000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': True,
        'image_url': 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&h=400&fit=crop&q=80',
        'description': "Climatiseur Samsung WindFree 9000 BTU avec diffusion douce sans jet d'air froid direct et WiFi SmartThings.",
        'specifications': {
            'Puissance': '9 000 BTU (1 CV)',
            'Technologie': 'WindFree + Digital Inverter',
            'WiFi': 'Oui (SmartThings)',
            'Classe energetique': 'A+++',
            'Filtre': 'Anti-bacterien + Filtre particulaire',
        },
    },
    {
        'name': 'Haier Split 12000 BTU Inverter WiFi',
        'slug': 'haier-split-12000-btu-inverter-wifi',
        'category_slug': 'climatiseurs',
        'brand': 'Haier',
        'price': 255000,
        'old_price': 290000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&h=400&fit=crop&q=80',
        'description': 'Climatiseur Haier Split 12000 BTU avec Inverter, WiFi integre et auto-nettoyage. Rapport qualite/prix imbattable.',
        'specifications': {
            'Puissance': '12 000 BTU (1.5 CV)',
            'Technologie': 'DC Inverter',
            'WiFi': 'Oui (hOn App)',
            'Auto-nettoyage': 'Oui',
            'Garantie compresseur': '5 ans',
        },
    },

    # ── REFRIGERATEURS ────────────────────────────────────────────────────────
    {
        'name': 'Hisense Fontaine a Eau avec Frigo',
        'slug': 'hisense-fontaine-eau-avec-frigo',
        'category_slug': 'refrigerateurs',
        'brand': 'Hisense',
        'price': 95000,
        'old_price': 115000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': True,
        'image_url': 'https://nova.sn/37171-home_default/fontaine-a-eau-hisense-avec-frigo-h85wdtp2s1dr.jpg',
        'description': 'Fontaine a eau Hisense avec refrigerateur integre (H85WDTP2S1DR). Eau fraiche et froide en permanence.',
        'specifications': {
            'Type': 'Fontaine avec frigo integre',
            'Capacite frigo': '5 litres',
            'Temperature': '5-15 degres C',
            'Couleur': 'Gris argent',
            'Garantie': '1 an',
        },
    },
    {
        'name': 'Hisense Fontaine a Eau Noire avec Frigo',
        'slug': 'hisense-fontaine-eau-noire-avec-frigo',
        'category_slug': 'refrigerateurs',
        'brand': 'Hisense',
        'price': 110000,
        'old_price': None,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': True,
        'image_url': 'https://nova.sn/41634-home_default/fontaine-a-eau-hisense-noir-h96wdtb3s1r-avec-refrigerateur-integre.jpg',
        'description': 'Fontaine a eau Hisense Noire (H96WDTB3S1R) avec refrigerateur integre. Design moderne adapte aux bureaux et maisons.',
        'specifications': {
            'Type': 'Fontaine avec frigo integre',
            'Capacite frigo': '10 litres',
            'Temperature': '5-15 degres C',
            'Couleur': 'Noir mat',
            'Garantie': '1 an',
        },
    },
    {
        'name': 'Samsung Refrigerateur 385L No Frost',
        'slug': 'samsung-refrigerateur-385l-no-frost',
        'category_slug': 'refrigerateurs',
        'brand': 'Samsung',
        'price': 385000,
        'old_price': 430000,
        'status': 'in_stock',
        'is_featured': True,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=400&h=400&fit=crop&q=80',
        'description': 'Refrigerateur Samsung 2 portes 385L No Frost avec technologie Metal Cooling et eclairage LED. Economie d\'energie A+.',
        'specifications': {
            'Capacite': '385 litres (269L frigo + 116L congelateur)',
            'Type': 'Double porte No Frost',
            'Classe energetique': 'A+',
            'Technologie': 'Metal Cooling',
            'Eclairage': 'LED',
            'Garantie': '1 an',
        },
    },
    {
        'name': 'LG Refrigerateur 335L Multi Air Flow',
        'slug': 'lg-refrigerateur-335l-multi-air-flow',
        'category_slug': 'refrigerateurs',
        'brand': 'LG',
        'price': 295000,
        'old_price': 340000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=400&h=400&fit=crop&q=80',
        'description': 'Refrigerateur LG 335L avec Multi Air Flow, Moist Balance Crisper et compresseur Inverter silencieux.',
        'specifications': {
            'Capacite': '335 litres',
            'Type': 'Double porte',
            'Compresseur': 'Inverter lineaire',
            'Refroidissement': 'Multi Air Flow',
            'Garantie compresseur': '10 ans',
        },
    },
    {
        'name': 'Haier Refrigerateur 70L Mini Bar',
        'slug': 'haier-refrigerateur-70l-mini-bar',
        'category_slug': 'refrigerateurs',
        'brand': 'Haier',
        'price': 85000,
        'old_price': 99000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=400&h=400&fit=crop&q=80',
        'description': 'Mini refrigerateur Haier 70L ideal pour chambre, bureau ou petite cuisine. Silencieux et economique.',
        'specifications': {
            'Capacite': '70 litres',
            'Type': '1 porte minibar',
            'Niveau sonore': '39 dB',
            'Classe energetique': 'A+',
        },
    },

    # ── MACHINES A LAVER ──────────────────────────────────────────────────────
    {
        'name': 'Samsung Lave-Linge 7Kg AddWash Inverter',
        'slug': 'samsung-lave-linge-7kg-addwash-inverter',
        'category_slug': 'machines-laver',
        'brand': 'Samsung',
        'price': 289000,
        'old_price': 339000,
        'status': 'in_stock',
        'is_featured': True,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&q=80',
        'description': 'Machine a laver Samsung 7 kg avec AddWash (ajouter du linge en cours), moteur Inverter Digital et classe A+++.',
        'specifications': {
            'Capacite': '7 kg',
            'Vitesse essorage': '1200 tr/min',
            'Classe energetique': 'A+++',
            'Technologie': 'AddWash + Eco Bubble',
            'Programmes': '18',
            'Garantie moteur': '10 ans',
        },
    },
    {
        'name': 'LG Lave-Linge 9Kg A+++ Inverter Direct Drive',
        'slug': 'lg-lave-linge-9kg-inverter-direct-drive',
        'category_slug': 'machines-laver',
        'brand': 'LG',
        'price': 345000,
        'old_price': 399000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&q=80',
        'description': 'Machine a laver LG 9 kg avec moteur Direct Drive 6 mouvement, Steam+ pour eliminer les allergenes et WiFi ThinQ.',
        'specifications': {
            'Capacite': '9 kg',
            'Vitesse essorage': '1400 tr/min',
            'Classe energetique': 'A+++',
            'Moteur': 'Direct Drive (garanti 10 ans)',
            'WiFi': 'Oui (ThinQ)',
            'Programmes': '14',
        },
    },
    {
        'name': 'Whirlpool Lave-Linge 6Kg',
        'slug': 'whirlpool-lave-linge-6kg',
        'category_slug': 'machines-laver',
        'brand': 'Whirlpool',
        'price': 195000,
        'old_price': 229000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&q=80',
        'description': 'Machine a laver Whirlpool 6 kg avec technologie 6eme Sens pour ajuster automatiquement eau et energie.',
        'specifications': {
            'Capacite': '6 kg',
            'Vitesse essorage': '1000 tr/min',
            'Classe energetique': 'A++',
            'Technologie': '6eme Sens',
            'Programmes': '12',
        },
    },

    # ── PETITS ELECTROMENAGERS ────────────────────────────────────────────────
    {
        'name': 'Philips Blender 2L 700W',
        'slug': 'philips-blender-2l-700w',
        'category_slug': 'petits-electromenagers',
        'brand': 'Philips',
        'price': 45000,
        'old_price': 55000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=400&h=400&fit=crop&q=80',
        'description': 'Blender Philips 2L 700W avec lames ProBlend en etoile, bol en verre et programme smoothie automatique.',
        'specifications': {
            'Capacite': '2 litres',
            'Puissance': '700W',
            'Bol': 'Verre borosilicate',
            'Vitesses': '2 + pulse',
            'Lames': 'ProBlend 6 etoile',
        },
    },
    {
        'name': 'Bosch Micro-ondes 20L 800W',
        'slug': 'bosch-micro-ondes-20l-800w',
        'category_slug': 'petits-electromenagers',
        'brand': 'Bosch',
        'price': 95000,
        'old_price': 115000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=400&h=400&fit=crop&q=80',
        'description': 'Micro-ondes Bosch 20L 800W avec grill integre, ecran LED et 5 niveaux de puissance. Design compact et elegant.',
        'specifications': {
            'Capacite': '20 litres',
            'Puissance': '800W',
            'Grill': '1000W',
            'Niveaux': '5',
            'Minuterie': '35 minutes',
        },
    },
    {
        'name': 'Philips Fer a Repasser Vapeur 2800W',
        'slug': 'philips-fer-repasser-vapeur-2800w',
        'category_slug': 'petits-electromenagers',
        'brand': 'Philips',
        'price': 22000,
        'old_price': 28000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1558171813-0d3e3d53e432?w=400&h=400&fit=crop&q=80',
        'description': 'Fer a repasser Philips 2800W avec semelle SteamGlide, jet vapeur 160g/s et debit vapeur continu 50g/min.',
        'specifications': {
            'Puissance': '2800W',
            'Vapeur continue': '50 g/min',
            'Jet vapeur': '160 g/s',
            'Semelle': 'SteamGlide',
            'Reservoir': '350 ml',
        },
    },
    {
        'name': 'Haier Climatiseur Portable 12000 BTU',
        'slug': 'haier-climatiseur-portable-12000-btu',
        'category_slug': 'petits-electromenagers',
        'brand': 'Haier',
        'price': 199000,
        'old_price': 240000,
        'status': 'out_of_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&h=400&fit=crop&q=80',
        'description': "Climatiseur portable Haier 12000 BTU sans installation fixe. Refroidit rapidement jusqu'a 25 m2.",
        'specifications': {
            'Puissance': '12 000 BTU',
            'Type': 'Portable',
            'Surface': "Jusqu'a 25 m2",
            'Mode': 'Froid/Deshumidification/Ventilation',
            'Telecommande': 'Incluse',
        },
    },

    # ── ONDULEURS ─────────────────────────────────────────────────────────────
    {
        'name': 'Onduleur Mercury Elite 1200VA Pro',
        'slug': 'onduleur-mercury-elite-1200va-pro',
        'category_slug': 'onduleurs-solaire',
        'brand': 'Haier',
        'price': 75000,
        'old_price': 89000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://nova.sn/40508-home_default/onduleur-mercury-elite-1200-pro-1200va-720w-protection-complete-et-avr.jpg',
        'description': 'Onduleur Mercury Elite 1200VA/720W avec AVR (regulateur automatique), ecran LCD et protection complete contre les surtensions.',
        'specifications': {
            'Puissance': '1200 VA / 720W',
            'Regulation': 'AVR integre',
            'Affichage': 'Ecran LCD',
            'Prises protegees': '4 prises universelles',
            'Duree de bascule': '< 6ms',
            'Garantie': '1 an',
        },
    },
    {
        'name': 'Onduleur Eaton Ellipse 1200VA',
        'slug': 'onduleur-eaton-ellipse-1200va',
        'category_slug': 'onduleurs-solaire',
        'brand': 'Philips',
        'price': 115000,
        'old_price': None,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&h=400&fit=crop&q=80',
        'description': 'Onduleur Eaton Ellipse 1200VA/750W avec AVR et 6 prises protegees. Ideal pour PC de bureau et peripheriques.',
        'specifications': {
            'Puissance': '1200 VA / 750W',
            'Regulation': 'AVR integre',
            'Prises': '6 prises IEC',
            'Port USB': 'Oui (surveillance)',
            'Logiciel': 'Eaton IPM inclus',
            'Garantie': '2 ans',
        },
    },
    {
        'name': 'Kit Solaire 200W Batterie 100Ah',
        'slug': 'kit-solaire-200w-batterie-100ah',
        'category_slug': 'onduleurs-solaire',
        'brand': 'Haier',
        'price': 289000,
        'old_price': 329000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': True,
        'image_url': 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400&h=400&fit=crop&q=80',
        'description': 'Kit solaire complet 200W avec 2 panneaux 100W, batterie 100Ah, regulateur MPPT et onduleur 1000W. Autosuffisance energetique.',
        'specifications': {
            'Panneaux': '2 x 100W monocristallin',
            'Batterie': '100 Ah AGM',
            'Regulateur': 'MPPT 30A',
            'Onduleur': '1000W pur sinus',
            'Applications': 'Maison, boutique, bureau',
        },
    },

    # ── HOME CINEMA & AUDIO ───────────────────────────────────────────────────
    {
        'name': 'LG Home Cinema 1250W Bluetooth',
        'slug': 'lg-home-cinema-1250w-bluetooth',
        'category_slug': 'home-cinema',
        'brand': 'LG',
        'price': 285000,
        'old_price': 320000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://nova.sn/37160-home_default/home-cinema-lg-1250-watt-lhd687bg-puissance-et-elegance.jpg',
        'description': 'Home Cinema LG 1250W (LHD687BG) systeme 5.1 avec Bluetooth, USB et lecture DVD. Son surround immersif.',
        'specifications': {
            'Puissance totale': '1250W RMS',
            'Canaux': '5.1 (5 enceintes + 1 caisson)',
            'Bluetooth': 'Oui',
            'Connectique': 'HDMI, USB, optique, coaxial',
            'Garantie': '1 an',
        },
    },
    {
        'name': 'LG Home Cinema 330W 5.1',
        'slug': 'lg-home-cinema-330w-51',
        'category_slug': 'home-cinema',
        'brand': 'LG',
        'price': 145000,
        'old_price': 175000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://nova.sn/37162-home_default/home-cinema-lg-330-watt-lhd457-son-surround-51-puissant-et-immersif.jpg',
        'description': 'Home Cinema LG LHD457 330W systeme 5.1 avec son surround immersif, USB et Bluetooth.',
        'specifications': {
            'Puissance': '330W RMS', 'Canaux': '5.1',
            'Bluetooth': 'Oui', 'USB': 'Oui (lecture MP3/WMA)',
            'Garantie': '1 an',
        },
    },
    {
        'name': 'Sony Soundbar HT-S400 330W',
        'slug': 'sony-soundbar-ht-s400-330w',
        'category_slug': 'home-cinema',
        'brand': 'Sony',
        'price': 185000,
        'old_price': 220000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': True,
        'image_url': 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=400&h=400&fit=crop&q=80',
        'description': 'Soundbar Sony HT-S400 330W avec subwoofer sans fil, Dolby Atmos et son 360 Spatial Sound.',
        'specifications': {
            'Puissance': '330W RMS',
            'Subwoofer': 'Sans fil inclus',
            'Format': '2.1 canaux',
            'Audio': 'Dolby Atmos, DTS:X',
            'Bluetooth': '5.0',
            'Connectique': 'HDMI ARC, optique, USB',
        },
    },

    # ── ENCEINTES BLUETOOTH ───────────────────────────────────────────────────
    {
        'name': 'JBL Charge 5 Enceinte Bluetooth',
        'slug': 'jbl-charge-5-enceinte-bluetooth',
        'category_slug': 'enceintes-bluetooth',
        'brand': 'JBL',
        'price': 89000,
        'old_price': 109000,
        'status': 'in_stock',
        'is_featured': True,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop&q=80',
        'description': 'JBL Charge 5 enceinte portable Bluetooth avec son Pro Sound 360, autonomie 20h et resistance IP67.',
        'specifications': {
            'Autonomie': '20 heures',
            'Bluetooth': '5.1',
            'Etancheite': 'IP67 (eau et poussiere)',
            'PowerBank': 'Oui (charge smartphones)',
            'Poids': '960g',
        },
    },
    {
        'name': 'JBL Flip 6 Enceinte Portable',
        'slug': 'jbl-flip-6-enceinte-portable',
        'category_slug': 'enceintes-bluetooth',
        'brand': 'JBL',
        'price': 59000,
        'old_price': 75000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop&q=80',
        'description': 'JBL Flip 6 enceinte portable compacte avec son stereo puissant, 12h d\'autonomie et IP67.',
        'specifications': {
            'Autonomie': '12 heures',
            'Bluetooth': '5.1',
            'Etancheite': 'IP67',
            'Poids': '530g',
            'Couplage': 'PartyBoost (plusieurs enceintes JBL)',
        },
    },
    {
        'name': 'Sony SRS-XB43 Enceinte Extra Bass',
        'slug': 'sony-srs-xb43-enceinte-extra-bass',
        'category_slug': 'enceintes-bluetooth',
        'brand': 'Sony',
        'price': 75000,
        'old_price': 95000,
        'status': 'low_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop&q=80',
        'description': 'Sony SRS-XB43 enceinte Extra Bass avec eclairage LED multicolore, 24h autonomie et IP67.',
        'specifications': {
            'Autonomie': '24 heures',
            'Bluetooth': '5.0',
            'Etancheite': 'IP67',
            'Eclairage': 'LED multicolore',
            'Bass': 'Extra Bass boost',
        },
    },

    # ── CAMERAS & SURVEILLANCE ────────────────────────────────────────────────
    {
        'name': 'EZVIZ C7 Dual Camera WiFi 2K+',
        'slug': 'ezviz-c7-dual-camera-wifi-2k',
        'category_slug': 'cameras-surveillance',
        'brand': 'Hisense',
        'price': 75000,
        'old_price': 90000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': True,
        'image_url': 'https://nova.sn/42285-home_default/camera-wifi-ezviz-c7-dual-2k-double-objectif-motorisee.jpg',
        'description': 'Camera EZVIZ C7 Dual 2K+ avec double objectif motorise, detection IA et vision nocturne couleur.',
        'specifications': {
            'Resolution': '2K+ (4 MP)',
            'Objectifs': 'Dual motorise panoramique + tilt',
            'Vision nocturne': 'Couleur (10m)',
            'Detection IA': 'Personnes, vehicules',
            'Stockage': 'MicroSD 256 Go + Cloud',
            'Etancheite': 'IP67',
        },
    },
    {
        'name': 'EZVIZ EB5 Camera Solaire 4K',
        'slug': 'ezviz-eb5-camera-solaire-4k',
        'category_slug': 'cameras-surveillance',
        'brand': 'Hisense',
        'price': 90000,
        'old_price': None,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': True,
        'image_url': 'https://nova.sn/42263-home_default/camera-solaire-ezviz-eb5-4k-sans-fil-avec-detection-ia.jpg',
        'description': 'Camera solaire EZVIZ EB5 4K sans fil avec panneau solaire integre, detection IA et IP67.',
        'specifications': {
            'Resolution': '4K (8 MP)',
            'Alimentation': 'Panneau solaire + batterie 10400 mAh',
            'Detection IA': 'Personnes, animaux, vehicules',
            'Etancheite': 'IP67',
            'Stockage': 'MicroSD 256 Go + Cloud',
        },
    },
    {
        'name': 'Kit 4 Cameras AHD 2MP Full HD DVR',
        'slug': 'kit-4-cameras-ahd-2mp-full-hd-dvr',
        'category_slug': 'cameras-surveillance',
        'brand': 'Hisense',
        'price': 145000,
        'old_price': 175000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=400&h=400&fit=crop&q=80',
        'description': 'Kit video surveillance complet : 4 cameras AHD 2MP Full HD + DVR 8 canaux + disque dur 1To. Installation facile.',
        'specifications': {
            'Cameras': '4 cameras dome 2MP Full HD',
            'DVR': '8 canaux H.265',
            'Stockage': 'Disque dur 1 To inclus',
            'Vision nocturne': '30m IR',
            'Acces distant': 'App mobile incluse',
            'Etancheite': 'IP66',
        },
    },

    # ── JEUX VIDEO ────────────────────────────────────────────────────────────
    {
        'name': 'PlayStation 5 Standard Edition',
        'slug': 'playstation-5-standard-edition',
        'category_slug': 'consoles',
        'brand': 'Sony',
        'price': 599000,
        'old_price': 650000,
        'status': 'low_stock',
        'is_featured': True,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400&h=400&fit=crop&q=80',
        'description': 'PlayStation 5 Standard Edition avec lecteur Blu-Ray 4K, SSD ultra-rapide 825 Go et manette DualSense.',
        'specifications': {
            'Stockage': 'SSD 825 Go',
            'Resolution': "Jusqu'a 8K / 4K 120fps",
            'Lecteur': 'Blu-Ray 4K Ultra HD',
            'Manette': 'DualSense incluse',
            'Puissance GPU': '10.28 TFLOPS',
            'Garantie': '1 an',
        },
    },
    {
        'name': 'PlayStation 5 Slim 1To',
        'slug': 'playstation-5-slim-1to',
        'category_slug': 'consoles',
        'brand': 'Sony',
        'price': 549000,
        'old_price': None,
        'status': 'in_stock',
        'is_featured': True,
        'is_new': True,
        'image_url': 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400&h=400&fit=crop&q=80',
        'description': 'PlayStation 5 Slim avec lecteur detachable en option, SSD 1 To et design 30% plus compact.',
        'specifications': {
            'Stockage': 'SSD 1 To',
            'Resolution': "Jusqu'a 8K / 4K 120fps",
            'Lecteur': 'Blu-Ray 4K Ultra HD detachable',
            'Manette': 'DualSense incluse',
            'WiFi': 'WiFi 6',
            'Garantie': '1 an',
        },
    },
    {
        'name': 'Xbox Series X 1To',
        'slug': 'xbox-series-x-1to',
        'category_slug': 'consoles',
        'brand': 'Microsoft',
        'price': 499000,
        'old_price': 549000,
        'status': 'in_stock',
        'is_featured': True,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=400&h=400&fit=crop&q=80',
        'description': 'Xbox Series X 1 To la plus puissante des consoles Xbox avec 12 TFLOPS, 4K 120fps et Quick Resume.',
        'specifications': {
            'Stockage': 'SSD NVMe 1 To',
            'Resolution': "Jusqu'a 8K / 4K 120fps",
            'GPU': '12 TFLOPS',
            'Lecteur': 'Blu-Ray 4K Ultra HD',
            'Quick Resume': 'Oui (reprise instantanee)',
            'Garantie': '1 an',
        },
    },
    {
        'name': 'Nintendo Switch OLED',
        'slug': 'nintendo-switch-oled',
        'category_slug': 'consoles',
        'brand': 'Nintendo',
        'price': 295000,
        'old_price': 330000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=400&h=400&fit=crop&q=80',
        'description': 'Nintendo Switch OLED avec ecran OLED 7 pouces vibrant, 64 Go de stockage et support ajustable large.',
        'specifications': {
            'Ecran': '7 pouces OLED 1280x720',
            'Stockage': '64 Go',
            'Autonomie': '4.5 - 9 heures',
            'Mode': 'TV / Portable / Tablette',
            'WiFi': '802.11ac',
        },
    },
    {
        'name': 'Manette DualSense PlayStation 5 Blanche',
        'slug': 'manette-dualsense-ps5-blanche',
        'category_slug': 'manettes-accessoires',
        'brand': 'Sony',
        'price': 59000,
        'old_price': 70000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400&h=400&fit=crop&q=80',
        'description': 'Manette DualSense PS5 officielle avec retour haptique adaptatif et gachettes a resistance variable.',
        'specifications': {
            'Compatibilite': 'PlayStation 5',
            'Retour haptique': 'Oui',
            'Gachettes adaptatives': 'Oui',
            'Microphone': 'Integre',
            'USB': 'USB-C',
            'Autonomie': '12 heures',
        },
    },
    {
        'name': 'Manette Xbox Series Noire',
        'slug': 'manette-xbox-series-noire',
        'category_slug': 'manettes-accessoires',
        'brand': 'Microsoft',
        'price': 49000,
        'old_price': 59000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=400&h=400&fit=crop&q=80',
        'description': 'Manette Xbox Series X/S officielle compatible Xbox et PC Windows avec bouton Share et Bluetooth.',
        'specifications': {
            'Compatibilite': 'Xbox Series X/S, Xbox One, PC Windows 10+',
            'Bluetooth': '4.2',
            'USB': 'USB-C',
            'Bouton Share': 'Oui',
            'Piles': '2 x AA',
        },
    },
    {
        'name': 'Casque Gaming Sony PULSE 3D Blanc',
        'slug': 'casque-gaming-sony-pulse-3d-blanc',
        'category_slug': 'manettes-accessoires',
        'brand': 'Sony',
        'price': 79000,
        'old_price': 99000,
        'status': 'in_stock',
        'is_featured': False,
        'is_new': False,
        'image_url': 'https://images.unsplash.com/photo-1583394293214-0c61e7d5f9fe?w=400&h=400&fit=crop&q=80',
        'description': 'Casque sans fil Sony PULSE 3D PS5 avec Tempest 3D Audio, double microphone et 12h autonomie.',
        'specifications': {
            'Compatibilite': 'PlayStation 5, PlayStation 4',
            'Audio': 'Tempest 3D Audio',
            'Microphone': 'Double microphone integre',
            'Sans fil': 'Oui (adaptateur USB inclus)',
            'Autonomie': '12 heures',
        },
    },
]


def download_image(url: str, filename: str):
    try:
        req = urllib.request.Request(
            url,
            headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
        )
        with urllib.request.urlopen(req, timeout=15) as resp:
            data = resp.read()
        if len(data) < 1000:
            return None
        return ContentFile(data, name=filename)
    except Exception:
        return None


class Command(BaseCommand):
    help = 'Cree des donnees de test pour le developpement'

    def handle(self, *args, **options):
        self.stdout.write('Creation des categories...')
        self._create_categories()
        self.stdout.write('Creation des marques...')
        self._create_brands()
        self.stdout.write('Creation des produits...')
        self._create_products()
        self.stdout.write(self.style.SUCCESS('\nTermine !'))

    def _create_categories(self):
        for cat_data in CATEGORIES:
            children = cat_data.pop('children', [])
            image_url = cat_data.pop('image_url', None)

            parent, created = Category.objects.get_or_create(
                slug=cat_data['slug'], defaults=cat_data)
            if created:
                self.stdout.write(f'  {parent.name}')

            if image_url and not parent.image:
                content = download_image(image_url, f'{parent.slug}.jpg')
                if content:
                    parent.image.save(f'{parent.slug}.jpg', content, save=True)
                    self.stdout.write(self.style.SUCCESS(f'    Image OK'))
                else:
                    self.stdout.write(self.style.WARNING(f'    Image ECHEC'))

            for child_data in children:
                child, created = Category.objects.get_or_create(
                    slug=child_data['slug'],
                    defaults={**child_data, 'parent': parent})
                if created:
                    self.stdout.write(f'    {child.name}')

            cat_data['children'] = children
            cat_data['image_url'] = image_url

    def _create_brands(self):
        for name in BRANDS:
            slug = slugify(name)
            Brand.objects.get_or_create(
                slug=slug,
                defaults={'name': name, 'is_featured': name in FEATURED_BRANDS})

    def _create_products(self):
        for p in SAMPLE_PRODUCTS:
            try:
                category = Category.objects.get(slug=p['category_slug'])
                brand = Brand.objects.filter(name=p['brand']).first()
                if not brand:
                    slug = slugify(p['brand'])
                    brand, _ = Brand.objects.get_or_create(
                        slug=slug, defaults={'name': p['brand'], 'is_featured': False})
            except Category.DoesNotExist as e:
                self.stdout.write(self.style.WARNING(f'  Ignore : {p["name"]} ({e})'))
                continue

            product, created = Product.objects.get_or_create(
                slug=p['slug'],
                defaults={
                    'name': p['name'], 'category': category, 'brand': brand,
                    'price': p['price'], 'old_price': p.get('old_price'),
                    'status': p['status'], 'is_featured': p['is_featured'],
                    'is_new': p['is_new'], 'description': p['description'],
                    'specifications': p['specifications'],
                })
            if created:
                self.stdout.write(f'  {product.name}')

            if not product.images.exists() and p.get('image_url'):
                self._add_image(product, p['image_url'])

    def _add_image(self, product, image_url):
        content = download_image(image_url, f'{product.slug}.jpg')
        if content:
            img = ProductImage(product=product, is_primary=True, order=0, alt_text=product.name)
            img.image.save(f'{product.slug}.jpg', content, save=True)
            self.stdout.write(self.style.SUCCESS(f'    Image OK'))
        else:
            self.stdout.write(self.style.WARNING(f'    Image ECHEC : {product.name}'))
